### ISSUE TITLE
Check flair models for static embeddings

### ISSUE THREAD

**Issue by ktagowski** [CLARIN-PL/embeddings#151]
Test flair models for static embeddings. Compare our pipeline results with results in literature or other leaderboards

**Comment by djaniak** [comment]
The static embeddings work fine with the flair pipelines, achieving satisfactory results when evaluated on polemo2 dataset (text classification).
The HPS pipeline was run for 100 iterations with the following outcome:
<details>
  <summary>HPS results</summary>
  
 ![image](https://user-images.githubusercontent.com/26749468/148930912-dd8f61a2-9fe5-4ad8-b7dc-8b794d57033a.png)
  
</details>

These results were compare with the ones reported in two papers:
- original publication that introduced the datasets: [Multi-Level Sentiment Analysis of PolEmo 2.0:
Extended Corpus of Multi-Domain Consumer Reviews](https://aclanthology.org/K19-1092.pdf)
- and publication with KLEJ benchmark: [KLEJ: Comprehensive Benchmark for Polish Language Understanding](https://arxiv.org/pdf/2005.00630.pdf)
