### ISSUE TITLE
Adding QA Pipeline 

### ISSUE THREAD

**Issue by laugustyniak** [CLARIN-PL/embeddings#278]
- @ktagowski can you add experimental code for QA that we have already created as starting point?

**Comment by ktagowski** [comment]
TODO @mkossakowski19 : 

- [ ]  Refactor Q&A code
- [ ] Tests on English Squad and add example of usage
- [ ] Tests on Polish translated Squad

**Comment by ktagowski** [comment]
TODO (17.02): 
- [ ]  Add tests for the QA evaluator
- [ ]  Adjust tests for pipeline 
Fix errors and add more detailed metrics checks. Currently, in tests, metrics are compared as `0 < mt < 100`, but it should be changed to 7 decimal precision, e.g., `assert_almost_equal(mt, 0.1234567)`.
- [ ] * Move batch encoding kwargs to LightningBasicConfig class
Create `QALightningBasicConfig` that is more suited for QA (2 batch_encoding parameters and 1 QA-specific parameter (`doc_stride`)
- [ ] * Fix linter
There are issues with styling and pymagnitude

Optional tasks (lower priority):
- [ ] * [optional] Adjust LightningModule class logic
Currently, there is code duplication between LightningModules (`setup`, `freeze_transformer`, `forward`). However, it needs restructuration of the inheritance hierarchy as `HuggingFaceLightningModule` are specific for Classification tasks.
- [ ] * [optional] Notebook with QA pipeline example
Add an example how "easy" it is to run a QA pipeline
